### PR TITLE
Create setting-up.md

### PR DESCRIPTION
**Pull request by Mehver**
https://github.com/chunkaligned/fabric-discord-integration/issues/20

### CODE REVIEW

**Comment by Mehver** [comment]
https://github.com/Mehver/fabric-discord-integration/blob/master/docs/setting-up.md

You can get a visual preview here.

**Comment by hkva** [comment]
Thanks

**Comment by Mehver** [comment]
I've noticed something curious: when you move a file's path using `git mv`, GitHub seems unable to correctly mark the file as my contribution. This is the first time I've encountered this, so I'm just venting a bit 😂. Of course, this minor contribution to the documentation is not really significant.

**Comment by hkva** [comment]
Strange, you still show as a contributor for me:
image

**Comment by Mehver** [comment]
Oh yes, when I checked the interface again, it displayed correctly, thank you for telling me. However, it seems to appear and disappear intermittently. After I refreshed it again, it vanished, and the same thing happened with other browsers. This is the mystery of GitHub, and it's my first time encountering it. A magical effect indeed. Perhaps it's due to the influence of workflows or `git mv`, causing some components on GitHub's servers not to be updated yet. I'm just amused to have discovered this peculiar phenomenon, please don't mind it.

**Pull request merged**
